server.port=8080
spring.application.name=gnomish-army-knife

# NAS
#spring.datasource.url=jdbc:postgresql://greennas:15432/mydb
#spring.datasource.username=postgres
#spring.datasource.password=MillerChu6983

# ??
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mydb
spring.datasource.username=millerchu
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
mybatis-plus.configuration.map-underscore-to-camel-case=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql