server.port=8080
spring.application.name=gnomish-army-knife
spring.datasource.url=jdbc:postgresql://192.168.31.135:15432/mydb
spring.datasource.username=postgres
spring.datasource.password=MillerChu6983
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis-plus.configuration.map-underscore-to-camel-case=true